//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_CITASMEDICAS.Moldes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        public int idCitas { get; set; }
        public int idPaciente { get; set; }
        public string ctCodigo { get; set; }
        public System.DateTime ctFechaRegistro { get; set; }
        public System.DateTime ctFechaCita { get; set; }
        public string ctEspecialidad { get; set; }
        public string ctMedico { get; set; }
        public string ctEstado { get; set; }
        public string ctDiagnostico { get; set; }
        public Nullable<decimal> ctCosto { get; set; }
    
        public virtual Pacientes Pacientes { get; set; }
    }
}
